version: "3.8"

services:
  referal:
    build: .
    container_name: referal
    command: python main.py
    restart: always
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/app/data     # вот эта строка защищает базу
